In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# Numpy 学习实践笔记


In [2]:
class1 = np.array([[True,80,177.7,'名字'],[1,2,3,4]])

In [3]:
class1

array([['True', '80', '177.7', '名字'],
       ['1', '2', '3', '4']], dtype='<U32')

In [4]:
class2 = np.array([[True,0,1989,-1,1,'不二'],[2,3,4,5,6,9]])

In [5]:
class2

array([['True', '0', '1989', '-1', '1', '不二'],
       ['2', '3', '4', '5', '6', '9']], dtype='<U21')

In [6]:
class2.dtype

dtype('<U21')

In [7]:
class1.ndim

2

In [8]:
class1.shape

(2, 4)

In [9]:
d = pd.DataFrame([np.arange(5),np.array([5,6,7,8,9])])

In [10]:
d.ndim

2

In [11]:
class1[0:3]

array([['True', '80', '177.7', '名字'],
       ['1', '2', '3', '4']], dtype='<U32')

In [12]:
type(class2)

numpy.ndarray

In [13]:
class1.shape

(2, 4)

In [14]:
np.ndim(class1)

2

In [15]:
len(class1.shape) == class1.ndim

True

# 创建


In [16]:
# arange()
res = np.arange(1,20,3)

In [17]:
res

array([ 1,  4,  7, 10, 13, 16, 19])

In [18]:
# linspace(shape)
res = np.linspace(1,10,4,endpoint=False)

In [19]:
res

array([1.  , 3.25, 5.5 , 7.75])

In [20]:
# zeros(shape)
res = np.zeros((2,2,2,2))

In [21]:
res

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [22]:
# empty(shape)
res = np.empty((1,3,4))

In [23]:
res

array([[[4.68432686e-310, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000]]])

In [24]:
# full()
res = np.full((2,2,2),[3,4])

In [25]:
res

array([[[3, 4],
        [3, 4]],

       [[3, 4],
        [3, 4]]])

In [26]:
tmp = np.array([['兰',1],['鹏',2],['飞',2]])

In [27]:
# ones_like()
res = np.ones_like(tmp)

In [28]:
res

array([['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [29]:
# zeros_like()
res = np.zeros_like(tmp)

In [30]:
res

array([['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

In [31]:
# empty_like()
res = np.empty_like(tmp)

In [32]:
res

array([['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

In [33]:
# full_like()

In [34]:
res = np.full_like(tmp,'#')

In [35]:
res

array([['#', '#'],
       ['#', '#'],
       ['#', '#']], dtype='<U1')

In [36]:
# eye()
res = np.eye(5)

In [37]:
res

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
# identity()
res = np.identity(5)

In [39]:
res

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
# diag()
re = np.diag([1,2,3,4,5,6],5)

In [41]:
re

array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [42]:
d.values[0]

array([0, 1, 2, 3, 4])

In [43]:
d

0  1  2  3  4
0  0  1  2  3  4
1  5  6  7  8  9

In [44]:
d

0  1  2  3  4
0  0  1  2  3  4
1  5  6  7  8  9

In [45]:
d.sort_index(ascending=False)

0  1  2  3  4
1  5  6  7  8  9
0  0  1  2  3  4

In [46]:
d.sort_values(by=0,ascending=False)

0  1  2  3  4
1  5  6  7  8  9
0  0  1  2  3  4

In [47]:
np.random.rand(2)

array([0.57666881, 0.69224501])

In [48]:
# uniform()
res = np.random.uniform(0,100)

In [49]:
res

60.5594775065433

In [50]:
res = np.random.randint(100)

In [51]:
res

74

In [52]:
# randn() 标准正太分布

In [53]:
res = np.random.randn(2,2)

In [54]:
res

array([[ 0.42372878, -1.02860226],
       [-3.18553589, -1.05134419]])

In [55]:
a = pd.DataFrame(res)

In [56]:
a

0         1
0  0.423729 -1.028602
1 -3.185536 -1.051344

In [57]:
# normal()

In [58]:
np.random.normal(1.75,0.5)

2.0463732220509967

In [59]:
np.random.normal(1.75,0.5,50)

array([1.71805546, 0.72311739, 1.26870487, 2.24596599, 1.41440552,
       1.08803197, 2.16248742, 2.113019  , 2.65754772, 2.24864214,
       0.9257552 , 1.643988  , 1.53734412, 2.0550919 , 1.56749208,
       1.73123203, 1.27363184, 2.05291019, 1.06972647, 1.04553239,
       1.32692785, 1.42022615, 1.77465298, 1.5598991 , 1.08904718,
       2.37669423, 0.85968968, 1.96105334, 1.80230974, 2.20954455,
       1.89249988, 2.15804136, 1.12229539, 1.28072824, 0.96740098,
       1.21367796, 1.9548092 , 1.61822998, 2.39812108, 1.38654811,
       1.57067794, 1.3235806 , 1.33869274, 1.38829433, 2.08677892,
       1.21232395, 2.14648485, 2.18182282, 1.59861224, 1.45102268])

In [60]:
np.random.normal(1.75,0.5,(2,3))

array([[1.16473148, 2.14295992, 1.83047937],
       [1.93117452, 2.59427631, 1.83362911]])

In [61]:
# 相同的种子,相同的随机数 seed()
# 如果种子相同 随机函数也相同 那么得到的随机数 是固定的

In [62]:
np.random.seed(19)
np.random.randint(1,1000,(2,3))

array([[606, 623, 758],
       [355, 937,  20]])

In [63]:
np.random.seed(19)
np.random.randint(1,1000,(2,3))

array([[606, 623, 758],
       [355, 937,  20]])

In [64]:
res = np.random.randint(0,10,10)

In [65]:
res

array([4, 2, 8, 6, 2, 5, 1, 6, 2, 7])

In [66]:
# DataFrame 展示 ndarray

In [67]:
res = pd.DataFrame(re.reshape(11,11))

In [68]:
res

0  1  2  3  4  5  6  7  8  9  10
0   0  0  0  0  0  1  0  0  0  0   0
1   0  0  0  0  0  0  2  0  0  0   0
2   0  0  0  0  0  0  0  3  0  0   0
3   0  0  0  0  0  0  0  0  4  0   0
4   0  0  0  0  0  0  0  0  0  5   0
5   0  0  0  0  0  0  0  0  0  0   6
6   0  0  0  0  0  0  0  0  0  0   0
7   0  0  0  0  0  0  0  0  0  0   0
8   0  0  0  0  0  0  0  0  0  0   0
9   0  0  0  0  0  0  0  0  0  0   0
10  0  0  0  0  0  0  0  0  0  0   0

In [69]:
# 查询

In [70]:
res = np.random.randint(0,10,10)

In [71]:
res

array([7, 0, 7, 7, 9, 9, 4, 5, 5, 7])

In [72]:
res[[1,3,5]]

array([0, 7, 9])

In [73]:
res  = np.random.randint(1,100,(3,4,2))

In [74]:
res

array([[[93, 82],
        [67, 54],
        [36, 58],
        [56, 61]],

       [[70, 33],
        [50, 69],
        [55, 93],
        [82, 13]],

       [[84, 50],
        [46, 85],
        [18, 84],
        [70, 26]]])

In [75]:
res[:,1]

array([[67, 54],
       [50, 69],
       [46, 85]])

In [76]:
# np.where 返回指定元素所在位置索引
a = np.array([[1,2,3,4],[5,4,7,8]])
b = np.array([[1,2,3,4],[5,4,7,8],[1,4,3,2],[5,2,1,8]])

In [77]:
a

array([[1, 2, 3, 4],
       [5, 4, 7, 8]])

In [78]:
b

array([[1, 2, 3, 4],
       [5, 4, 7, 8],
       [1, 4, 3, 2],
       [5, 2, 1, 8]])

In [79]:
res=np.where(a>2)

In [80]:
res

(array([0, 0, 1, 1, 1, 1]), array([2, 3, 0, 1, 2, 3]))

In [81]:
# python 三元表达式
res = 1+1 if 1<0 else 2+5

In [82]:
np.where(b>3,'大于3','小于或等于3')

array([['小于或等于3', '小于或等于3', '小于或等于3', '大于3'],
       ['大于3', '大于3', '大于3', '大于3'],
       ['小于或等于3', '大于3', '小于或等于3', '小于或等于3'],
       ['大于3', '小于或等于3', '小于或等于3', '大于3']], dtype='<U6')

In [83]:
# 维度变换 .reshape()返回一个新的 .resize()改变原数组 .flatten()降维度

In [84]:
res = np.zeros((2,3,4))

In [85]:
res.resize(2,12)

In [86]:
res

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [87]:
res.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [88]:
#类型转换

In [89]:
res

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [90]:
res.dtype

dtype('float64')

In [91]:
#整型int
res = res.astype(np.int)
res.dtype

dtype('int64')

In [92]:
res

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [93]:
res

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [94]:
#布尔值bool
res1 = res.astype(np.bool)
res.dtype

dtype('int64')

In [95]:
res1

array([[False, False, False, False, False, False, False, False, False,
        False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False]])

In [96]:
#复数complex  此处忽略复数,会对字符串等类型有影响
#res = res.astype(np.complex)
#res.dtype

In [97]:
res

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [98]:
#对象object
res = res.astype(np.object)
res.dtype

dtype('O')

In [99]:
res

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=object)

In [100]:
#ASCII字符
ress = res.astype(np.string_)
ress.astype

<function ndarray.astype>

In [101]:
ress

array([[b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0',
        b'0'],
       [b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0',
        b'0']], dtype='|S1')

In [102]:
res

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=object)

In [103]:
#Unicode_ 所有字符 (字符串)
res = res.astype(np.unicode_)
res.dtype

dtype('<U1')

In [104]:
res

array([['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
       ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']],
      dtype='<U1')

# 运算

In [105]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
a + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [107]:
a - 10

array([[-9, -8, -7],
       [-6, -5, -4]])

In [108]:
a * 0.5

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [109]:
a /3 

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [110]:
a // 3

array([[0, 0, 1],
       [1, 1, 2]])

In [111]:
a % 3

array([[1, 2, 0],
       [1, 2, 0]])

In [112]:
a ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [113]:
a ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [114]:
a-1

array([[0, 1, 2],
       [3, 4, 5]])

In [115]:
a - np.full_like(a,1)

array([[0, 1, 2],
       [3, 4, 5]])

In [116]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [117]:
np.log2(a)

array([[0.        , 1.        , 1.5849625 ],
       [2.        , 2.32192809, 2.5849625 ]])

In [118]:
a[1,2]=-4
np.sign(a)

array([[ 1,  1,  1],
       [ 1,  1, -1]])

In [119]:
np.log2(1/32)

-5.0

In [120]:
2 ** -5

0.03125

In [121]:
1/32

0.03125

In [122]:
a

array([[ 1,  2,  3],
       [ 4,  5, -4]])

In [123]:
#求和
a.sum()

11

In [124]:
a

array([[ 1,  2,  3],
       [ 4,  5, -4]])

In [125]:
#求 累加 +=
a.cumsum()

array([ 1,  3,  6, 10, 15, 11])

In [126]:
#求 绝对值
np.abs(a)

array([[1, 2, 3],
       [4, 5, 4]])

In [127]:
#求 累乘
a.cumprod()

array([   1,    2,    6,   24,  120, -480])

In [128]:
#diff 相邻数组元素的差值
np.diff(a)

array([[ 1,  1],
       [ 1, -9]])

In [129]:
#mean()
a.mean()

1.8333333333333333

In [130]:
a

array([[ 1,  2,  3],
       [ 4,  5, -4]])

In [131]:
#median()
np.median(a)

2.5

In [132]:
# min()
a.min()

-4

In [133]:
# ptp() 求极差
a.ptp()

9

In [134]:
#var 方差
a.var()

8.472222222222221

In [135]:
#std 标准差
a.std()

2.91070819942883

In [136]:
res = np.arange(0,60).reshape(3,4,5)

In [137]:
res

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [138]:
res.sum(axis=2)

array([[ 10,  35,  60,  85],
       [110, 135, 160, 185],
       [210, 235, 260, 285]])

In [139]:
res.argmax()

59

In [140]:
res = np.random.randint(0,100,60)

In [141]:
res.argmin()

8

# 布尔值相关

## 也可用在非布尔型数组,非0 则被当作是True

In [142]:
bools = np.array([False,1,2,3])

In [143]:
# any() 是否有 True
bools.any()

True

In [144]:
# all() 全都是 True
bools.all()

False


# ndarray 操作


In [145]:
a = np.random.randint(1,100,50)

In [146]:
# 随机
-np.sort(-a)

array([95, 94, 90, 86, 86, 86, 85, 84, 82, 81, 80, 79, 74, 74, 69, 66, 64,
       57, 57, 55, 54, 52, 52, 44, 43, 40, 39, 39, 37, 30, 30, 30, 29, 28,
       26, 25, 25, 24, 23, 20, 19, 13,  7,  7,  6,  6,  5,  4,  4,  1])

In [147]:
res = res.reshape(3,4,5)
res

array([[[51, 91, 55,  9, 11],
        [93, 62, 60,  0, 35],
        [63, 31, 32, 63, 10],
        [87, 44, 90, 21, 67]],

       [[85, 58, 11, 41, 88],
        [48, 71, 65,  9, 26],
        [34, 55, 52, 97, 67],
        [74, 70, 76, 29, 90]],

       [[70, 19,  9, 21, 87],
        [28, 25, 46, 69,  4],
        [97, 44,  3, 73, 77],
        [25, 44, 47, 84, 45]]])

In [148]:
np.sort(res)

array([[[ 9, 11, 51, 55, 91],
        [ 0, 35, 60, 62, 93],
        [10, 31, 32, 63, 63],
        [21, 44, 67, 87, 90]],

       [[11, 41, 58, 85, 88],
        [ 9, 26, 48, 65, 71],
        [34, 52, 55, 67, 97],
        [29, 70, 74, 76, 90]],

       [[ 9, 19, 21, 70, 87],
        [ 4, 25, 28, 46, 69],
        [ 3, 44, 73, 77, 97],
        [25, 44, 45, 47, 84]]])

In [149]:
# 排序
np.sort(res,axis=2)

array([[[ 9, 11, 51, 55, 91],
        [ 0, 35, 60, 62, 93],
        [10, 31, 32, 63, 63],
        [21, 44, 67, 87, 90]],

       [[11, 41, 58, 85, 88],
        [ 9, 26, 48, 65, 71],
        [34, 52, 55, 67, 97],
        [29, 70, 74, 76, 90]],

       [[ 9, 19, 21, 70, 87],
        [ 4, 25, 28, 46, 69],
        [ 3, 44, 73, 77, 97],
        [25, 44, 45, 47, 84]]])

In [150]:
res

array([[[51, 91, 55,  9, 11],
        [93, 62, 60,  0, 35],
        [63, 31, 32, 63, 10],
        [87, 44, 90, 21, 67]],

       [[85, 58, 11, 41, 88],
        [48, 71, 65,  9, 26],
        [34, 55, 52, 97, 67],
        [74, 70, 76, 29, 90]],

       [[70, 19,  9, 21, 87],
        [28, 25, 46, 69,  4],
        [97, 44,  3, 73, 77],
        [25, 44, 47, 84, 45]]])

In [151]:
res.T

array([[[51, 85, 70],
        [93, 48, 28],
        [63, 34, 97],
        [87, 74, 25]],

       [[91, 58, 19],
        [62, 71, 25],
        [31, 55, 44],
        [44, 70, 44]],

       [[55, 11,  9],
        [60, 65, 46],
        [32, 52,  3],
        [90, 76, 47]],

       [[ 9, 41, 21],
        [ 0,  9, 69],
        [63, 97, 73],
        [21, 29, 84]],

       [[11, 88, 87],
        [35, 26,  4],
        [10, 67, 77],
        [67, 90, 45]]])

In [152]:
res2 = np.random.randint(1,100,(4,6))

In [153]:
res2.T

array([[43,  5, 59, 83],
       [62,  3, 64, 56],
       [82, 56, 43,  5],
       [71, 94, 77, 51],
       [60, 15, 69, 28],
       [ 4, 24,  8, 90]])

In [154]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [155]:
b = np.array([[10,11,12],[1,2,3],[1,2,3]])
b

array([[10, 11, 12],
       [ 1,  2,  3],
       [ 1,  2,  3]])

In [156]:
res = np.concatenate((a,b.T),axis=1)

In [157]:
res

array([[ 1,  2,  3, 10,  1,  1],
       [ 4,  5,  6, 11,  2,  2],
       [ 7,  8,  9, 12,  3,  3]])

In [158]:
# delete 
np.delete(res,-1,axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [ ]:
# 高级函数 
# shuffle(obj)
res = np.arange(1,61).reshape(3,4,5)
res 

In [ ]:
# permutation 不改变原数组
np.random.permutation(res)

In [ ]:
# choice 抽取对象必须是一维的
res = res.flatten()
res

In [ ]:
res = np.random.choice(res,size=(4,4,4),p=res/np.sum(res))

In [ ]:
res/np.sum(res)

In [ ]:
res

# 集合
## 是对不同集合 所有元素 进行对比
### unique(x) intersect1d(x,y) union1d(x,y) in1d(x,y) setdiff1d(x,y) setxor1d(x,y)

In [ ]:
a = np.array([6,0,0,3,2,5,6])
b = np.array([2,3,6,8])

In [ ]:
a

In [ ]:
b

In [ ]:
# unique(obj) 只去重
np.unique(a)

In [ ]:
# intersect1d(obj1,obj2) 交集升序
np.intersect1d(a,b)

In [ ]:
# union1d(obj1,obj2) 并集升序
np.union1d(a,b)

In [ ]:
# setdiff1d(obj1,obj2) 差集升序
np.setdiff1d(a,b)

In [ ]:
# in1d(obj1,obj2) obj1元素是否在obj2 中,返回 布尔数组
np.in1d(a,b)

In [ ]:
# setxor1d(obj1,obj2)
np.setxor1d(a,b)

In [ ]:
# 矩阵运算
x = np.array([[1,2],[3,4]])
x

In [ ]:
x[0].reshape(1,2).T

In [ ]:
x[0]

In [ ]:
x+x

In [ ]:
x*x

In [ ]:
x

In [ ]:
a = np.asarray([2,3,4,5])

In [ ]:
type(a)

# 点乘 dot

In [7]:
a = np.array([[5,2],[2,4]])
b = np.array([[3,2],[3,2]])
c = np.array([[3,2],[3,2]])

In [9]:
a

array([[5, 2],
       [2, 4]])

In [10]:
b

array([[3, 2],
       [3, 2]])

In [11]:
a.dot(b)

array([[21, 14],
       [18, 12]])

In [14]:
np.dot(a,b).dot(c)

array([[693, 462],
       [594, 396]])

In [15]:
# 总结 : 结果的每一个元素,是用a在行上的元素,每每乘以b在该列上的元素,再做加法,得到一个数字

In [16]:
a.dot(b).dot(c)

array([[693, 462],
       [594, 396]])

In [23]:
b.dot(b.T)

array([[13, 13],
       [13, 13]])

In [27]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [28]:
a

array([[5, 2],
       [2, 4]])

In [33]:
aT = np.array([[4,-2],[-2,5]])

In [36]:
aT = aT*1/16

In [39]:
a.dot(aT).astype(np.int)

array([[1, 0],
       [0, 1]])